jenkins-infra/crawler

sonarrunner.groovy

Sonar product was renamed SonarQube for trademark issues

SONARJNKNS-196 Rename Sonar -> SonarQube

---

cmake.groovy

Added cmake crawler for cmakebuilder Plugin

cmake crawler: cmake.org

---

cmake.groovy

tested with
```~/devel/src/backend-crawler> ./cmake.groovy ```

fixed unresolvable classes

---

groovy.groovy

JENKINS-31572 - sort Groovy versions by version, not filename.

---

sbt.groovy

http://scalasbt.artifactoryonline.com/scalasbt does not exist anymore, and this causes the Scala SBT crawler to fail.
FYI @ydubreuil

Remove Artifactory Online as data source

---

sonarqubescanner.groovy
sonarqubescannermsbuild.groovy

* The name of the 2 tools was changed.
* The groupId of SonarQube Runner was also changed
Relates to:
* https://jira.sonarsource.com/browse/SONARJNKNS-229
* https://jira.sonarsource.com/browse/SONARJNKNS-230

Few improvement for SonarQube Scanners

---

flyway.groovy

Reports the various versions of flyway that are available in maven central.
Intended to be used by the flyway runner plugin in an upcoming release.

added crawler to find flyway packages in maven central

---

consul.groovy

consul crawler for new jenkins plugin

Added new consul crawler

---

sonarqubescannermsbuild.groovy

The artifact was renamed
https://jira.sonarsource.com/browse/SONARMSBRU-287

SONARMSBRU-287 Update crawler for SonarQube Scanner for MSBuild

---

allure.groovy

This reverts commit a1e96f7f2dde232f71480968cca19533fef7a2e8.
@eroshenkoam As you haven't responded to my comments, I will revert your change for now to prevent breaking users.

Revert "allure2 integration"

---

jdk.groovy

Similar to PR #65 to add the archives page
cc @daniel-beck @batmat @mwaite @rtyler @oleg-nenashev 
I attached the generated file if you want to test it too
[hudson.tools.JDKInstaller.txt](https://github.com/jenkins-infra/crawler/files/1393944/hudson.tools.JDKInstaller.txt)

INFRA-1366 Add JDK 9 archives

---

sbt.groovy

SBT 1.0 (and newer) changed their download site. The new versions accessible from here: https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.0.1/
Here's the output from running this script locally. 
<details>
```
$ groovy -Dgrape.config=./grapeConfig.xml ./lib/runner.groovy sbt.groovy 
loading dependencies...done
{"list": [
{
"id": "1.1.0-M1",
"name": "1.1.0-M1",
"url": "https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.1.0-M1/sbt-1.1.0-M1.jar"
},
{
"id": "1.0.4",
"name": "1.0.4",
"url": "https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.0.4/sbt-1.0.4.jar"
},
{
"id": "1.0.3",
"name": "1.0.3",
"url": "https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.0.3/sbt-1.0.3.jar"
},
{
"id": "1.0.2",
"name": "1.0.2",
"url": "https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.0.2/sbt-1.0.2.jar"
},
{ …
```

crawl new sbt download site for 1.x

---

jdk.groovy

Please review @daniel-beck @oleg-nenashev

INFRA-1552: Add Oracle JDK 10 installer

---

jdk.groovy

JDK9 latest download page is no longer exists.

Java SE 9 has reached end of support.

---

adoptopenjdk.groovy

Currently the v2 api is not returning all releases. This PR switches to v3 which solves this problem. 
Also all HotSpot releases are grouped together instead of alternating between HotSpot/OpenJ9 in the list.

[JENKINS-62013] - Switched to v3 rest api

---

adoptopenjdk.groovy

#93 introduced a bug where the output includes a list of lists instead of a list of releases.

[JENKINS-62013] - Fix for list of lists introduced in #93

---

dependencycheck.groovy

I'm not 100% on how this system works, but this should fix things.
https://github.com/jeremylong/DependencyCheck/releases/tag/v6.0.2
https://issues.jenkins-ci.org/browse/JENKINS-63806

Dependency check downloads migrating to github

---

dotnetSdk.groovy

The authoritative RID catalog was moved again.
The next time this happens, I'll maintain a copy so that the location is stable.
Tweaked the SDK processing to handle more Alpine Linux archs correctly, and to only include one download per RID (linx-x64 had both .tar.gz and .zip).

Fix .NET SDK downloadables

---

lib/init.groovy
pom.xml

Use https for artifacts

---

allure.groovy
sbt.groovy

It was sunset by JFrog https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
It returns 403 Forbiden to all requests now

Complete the removal of Bintray

---

Jenkinsfile

Signed-off-by: Damien Duportal <damien.duportal@gmail.com>

chore(pipeline) fix a remaining sh interpolation

---

Jenkinsfile

I mistakenly triggered another inteprolation issue with #112 .
This PR should do the trick

chore(pipeline) fix withEnv interpolation

---

groovy.groovy

Fixes https://github.com/jenkins-infra/crawler/issues/119

fix(groovy.groovy): accept multiple digits in version parts

---

README.md
lib/signer.groovy

Ref. jenkins-infra/helpdesk#2950

feat(signer) add a new groovy lib script to allow signing (only) the json files

---

Jenkinsfile

Ref:
- https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-1808612479

feat: also sync to File Share and R2 buckets

---

sonarqubescannermsbuild.groovy

Update the filenames for versions 6.* of the scanner.

Update for sonar-scanner-msbuild version 6

---

Jenkinsfile

This PR switches the CD part of this project (running in trusted.ci.jenkins.io) to reuse the same credentials, introduced in https://github.com/jenkins-infra/update-center2/pull/787, as the jenkins-infra/update-center2 job.
It also avoids to repeat credentials between the 2 jobs (SSH key for instance...) and improves the configuration management (we change Rsync user/host/etc only once!)
Notes:
- The `azcopy-redirection` Azure file share won't need to be updated here as it only hosts the Apache `htaccess` files (as far as I can tell we don't have any `.htaccess` files in the `./updates/` directory in production: `find /var/www/updates.jenkins.io/updates/ -type f -name "*.htaccess" | wc -l` says `0`
- There is room for improvement: once we'll introduce new mirror SSH/S3 or other targets, …

chore(pipeline) use new trusted.ci ZIP credentials to deploy generated artefacts

---

.jenkins-scripts/publish.sh

Related to https://github.com/jenkins-infra/helpdesk/issues/4373#issuecomment-2450367622
This PR adds 2 new destination for the publication: the 2 Apache htdocs of the new Update center.
The goal is to ensure we can have a directory listing

chore(publish) add the 2 Apache destinations for publication to allow directory listing

---

.jenkins-scripts/publish.sh

Ref. https://github.com/jenkins-infra/helpdesk/issues/4500#issuecomment-2642644638

chore(publish.sh) pin `aws` CLI to `2.22.35`

---

.jenkins-scripts/publish.sh

as per https://github.com/jenkins-infra/helpdesk/issues/4500
tested with success on replay on https://trusted.ci.jenkins.io:1443/job/crawler/16244/

fix(crawler/publish): use the latest aws with the correct crc32 checksum-algorithm

---

.jenkins-scripts/publish.sh
Jenkinsfile

Ref. https://github.com/jenkins-infra/helpdesk/issues/4758#issuecomment-3159980783
Twin of https://github.com/jenkins-infra/update-center2/pull/882
The source branch of this PR is currently used on the trusted.ci `crawler` generation on trusted.ci.jenkins.io: merging it requires to update the job configuration to use */master branch again.
It ran successfully multiple times:
It introduces the following changes:
- Split pipeline in 2 steps, 1 per agent: 
- Build/generation always uses `maven-17` (instead of tools) to ensure coherent behavior between ci.jenkins.io and other controllers
- If running on trusted.ci, then stash/unstash generated data and proceed to publication using the permanent agent where the updates.jenkins.io NFS data volume is mounted
- Use the new "local rsync" …

chore(Jenkinsfile/publish) update publication process to the unified NFS + HTTPS update center
