- sbt.groovy
Current sbt tool definition is outdated as new sbt binaries are released on bintray.
This patch uses the bintray REST API to retrieve the new version list but still retrieve old versions list on scalasbt.artifactoryonline.com. If a version is found on bintray and scalasbt.artifactoryonline.com, bintray URL is preferred.
> Update sbt crawler to support new download site

- groovy.groovy
Groovy distributions are hosted on Bintray after Codehaus was shut down.
In line 15 I had to remove a leading # from the URL which is done by JavaScript on the Bintray page.
> [JENKINS-28502] fixed Groovy crawler

- packer.groovy
I guess bintray changed their URL prefix to be with % instead of #.
Everything else looks the same.
> Fix crawler due to bintray changes

- packer.groovy
JFrog opened up `/files` REST API call, so it's now possible to retrieve file listing directly. It will prevent failures due to changing HTML page format like in https://github.com/jenkinsci/backend-crawler/pull/36
@reviewbybees
> Use bintray API to compute packer tools list

- msbuildsonarquberunner.groovy
I'm not sure how to test that it works but this crawler is expected to list all releases from sonar-msbuild-runner project. This is linked to support of running SonarQube analysis with MSBuild:
https://jira.sonarsource.com/browse/SONARJNKNS-221
> Add crawler for MSBuild SonarQube Runner

- cmake.groovy
disable directory listing in general due to excessive traffic caused by
bots.
Give cmake.org a chance to complain directly.
> Send unique User-Agent header, as the download site is planning to

- terraform.groovy
This crawler downloads versions of Terraform from bintray.com for use with the terraform-plugin.
> Adding crawler for HashiCorp's Terraform

- chromedriver.groovy
Relates to issue https://issues.jenkins-ci.org/browse/JENKINS-33270 
Perhaps there's a better way to get the latest version number, but I am not familiar with groovy, and this seems to work.
> Correctly find the highest version number for chromedriver

- maven.groovy
archive.apache.org is really slow today due to a recent outage:  https://twitter.com/infrabot/status/717964322790445056 
This slowness fails a lot of builds because jenkins doesn't succeed to download Maven (enough quickly) before hiting the download timeout. 
I found a bug in our script which prefers to use archive.apache.org instead of Maven central which is wrong because archive.a.o isn't at all usable for massive downloads. 
With this fix we are using central for all releases >= 2.0.9 while before we were using it only for >= 3.2.3 :( 
I also switched to https like for many others tools
> URGENT: Builds are failing because Apache Maven cannot be downloaded (correctly) from archive.apache.org

- grails.groovy
The api that was being called was orphaned, so I wrote a new endpoint that serves the purpose required here. New versions will now show up as expected.
> Cut over to new sdkman endpoint for grails versions.

- flyway.groovy
Users complained about the non-availability auto-installers in dropdown.
https://issues.jenkins-ci.org/browse/JENKINS-44429
> Updated with proper and exact Flyway installer name

- jdk.groovy
Tested locally on macOS and it's ok.
```
Started by user admin
Building in workspace /Users/arnaud/Temp/j9/jenkins-home/workspace/j9
Installing JDK jdk-9-oth-JPR
Downloading JDK from http://download.oracle.com/otn-pub/java/jdk/9+181/jdk-9_osx-x64_bin.dmg
Downloading 389691100 bytes
Installing /Users/arnaud/Temp/j9/jenkins-home/tools/hudson.model.JDK/j9/jdk.dmg
$ hdiutil attach -puppetstrings -mountpoint /Users/arnaud/Temp/j9/jenkins-home/tools/hudson.model.JDK/jdk7442574252105268483dmg /Users/arnaud/Temp/j9/jenkins-home/tools/hudson.model.JDK/j9/jdk.dmg
PERCENT:0.000000
MESSAGE:Checksumming Protective Master Boot Record (MBR : 0)…
MESSAGE:
MESSAGE:Protective Master Boot Record (MBR :: verified   CRC32 $A63E199D
MESSAGE:Checksumming GPT Header (Primary GPT Header : 1)…
MESSAGE:
MESSAGE: …
```
> INFRA-1353 - Add JDK9 in JDKInstaller (not archives yet)

- sbt.groovy
Extending fro https://github.com/jenkins-infra/crawler/pull/67 the `.jar` downloads fail, but sbt offers `.zip` files that probably work the same as `0.13.x` installs.
> sbt: download 1.x artifacts from github, but source versions from maven

- gradle.groovy
Because the following errors occurred.
```
$ groovy -Dgrape.config=./grapeConfig.xml ./lib/runner.groovy gradle.groovy
loading dependencies...done
Caught: com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: TypeError: Expected argument of type object, but instead had type object (https://fast.wistia.com/static/embed_shepherd-v1.js#547) (gradle.groovy#10) (gradle.groovy#10) (gradle.groovy#10)
======= EXCEPTION START ========
Exception class=[net.sourceforge.htmlunit.corejs.javascript.WrappedException]
com.gargoylesoftware.htmlunit.ScriptException: Wrapped com.gargoylesoftware.htmlunit.ScriptException: Wrapped …
```
> Ignore JavaScript error in Gradle crawler.

- sonarqubescannermsbuild.groovy
Hi,
Sorry for this missed 1st PR.
We are currently working on our [Jenkins plugin](https://github.com/SonarSource/sonar-scanner-jenkins) to provide the ability for our end-users to user the .net core version of one of our product (scanner for msbuild). As part of this change we needed to update the crawler so that the users can select the scanner for .net core in the drop-down of the plugin configuration.
I put a `[do not merge]` in the title because we would like to be able to synchronize the release of our plugin with the availability of the new scanners in the drop-down to avoid (reduce is more appropriate) the number of support request we would/could receive from users.
Cheers,
Amaury
> Update crawler to list scanner for msbuild netcore

- allure.groovy
Allure moves to maven central (starting from 2.8.0) from generic (files) repository in bintray.
So this PR makes allure available from 2.8.0 version in Jenkins.
> Update allure location

- jdk.groovy
Will lose JDK 10 but, as Oracle helpfully informs us,
"Java SE 10 has reached end of support. Users of Java SE 10 should switch to Java SE 11."
> Restore JDK runner

- adoptopenjdk.groovy
- jdk.groovy
Crawler for downloading OpenJDK releases built by http://adoptopenjdk.net
Used by new plugin: https://github.com/hrmohr/adoptopenjdk-plugin
Hosting request pending: https://issues.jenkins-ci.org/browse/HOSTING-761
> Added crawler for adoptopenjdk.net

- dotnetSdk.groovy
It creates three files; two small ones used for autocompletion (one based on Microsoft-hosted data, one based on a file in the plugin repo pending a more authoritative source), and one big one for the SDK downloads (of which there are many; based on official Microsoft data).
To be used by https://github.com/jenkinsci/dotnet-sdk-plugin of which I am the maintainer; plugin changes to use these files are ready and tested.
> Add script for dotnet-sdk-plugin downloadables

- golang.groovy
Ticket: https://issues.jenkins-ci.org/browse/JENKINS-62887
The links provided on the download page no longer provide the absolute URL, so we need to add the prefix ourselves.
I ran the crawler and checked a bunch of the URLs — they looked fine.
> [FIXED JENKINS-62887] Fix for updated Go download page

- dotnetSdk.groovy
Microsoft changed the tree structure for dotnet/runtime, breaking the
download. The URL has been updated to the new/current location.
In addition, some error handling was added, so that failure for one
of the three output files does not prevent creation of the others. An
aggregate exception will be thrown at the end.
_Note: it would be really really nice to be able to detect/see crawler errors somewhere; I only noticed something was wrong because the latest 5.0 SDK wasn't in the list._
> Fix .NET SDK runtime info retrieval

- sonarqubescannermsbuild.groovy
Since the MSBuild sonar scanner release 5 (https://github.com/SonarSource/sonar-scanner-msbuild/releases/tag/5.0.0.23533) there is now officially support for .NET5 included in the releases. The crawler currently does not pick up or propagate the availability of .NET5 since it is not included in this groovy config. Adding the functionality here ensures the crawler publishes the availability of the new framework.
Separately, there may be a need to reconsider/refactor how the crawler works to take into account the changing nature of of framework version support coming from the sonar scanner for msbuild, so that manual updates and PRs like this aren't required each time there is a new .NET version.
> Add support for .NET5

- groovy.groovy
With Bintray going away, the Groovy team is hosting the zip distributions in https://groovy.jfrog.io/artifactory/dist-release-local/groovy-zips/ now (https://twitter.com/paulk_asert/status/1382103222446292996?s=20)
> Update groovy binaries location

- groovy.groovy
Bintray used to have a colon (':') prepended to the filename in the href attribute. This is no longer the case when we are using
the new mirror.
New mirror (https://groovy.jfrog.io/artifactory/dist-release-local/groovy-zips/)
Old mirror (https://dl.bintray.com/groovy/maven/)
> Stop stripping first char from filename

- maven.groovy
There are message digest files for the Maven metadata files in Maven central. Due to increased security these now include .sha256 and .sha512 files, and these match the pattern being used to find versions. The crawler fails to read these files as html-pages, so we need to ignore them.
> [INFRA-2963] crawler fails to fetch Maven versions

- dependencycheck.groovy
Starting with 6.0.4, the "name" value switched from "vX" to "Version X" while the "tag_name" value has remained consistent and in the expected format.
> Use "tag_name" instead of "name"

- dependencycheck.groovy
As of v6.1.2, dependency check releases are no longer published to bintray. bintray services are no longer available as of 2021-05-01.
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
> Remove bintray references

- dotnetSdk.groovy
This time it's just the rename of the `master` branch to `main`.
GitHub redirects the URL at the moment, so this is not all that urgent.
> Adjust the URL for the rid catalog (again)

- sonarqubescannermsbuild.groovy
The PR supplied in #96 uses the same ID for two different versions. I'm actually curious how the initial PR ever worked, but it doesn't do so now.
I added a unique ID for the net5.0 version, which should fix this.
I also changed the display name to better reflect the official name of .NET 5.0 which MS promotes for it.
> Fixed duplicate id for sonar-scanner-msbuild versions

- codeql.groovy
Crawler for downloading CodeQL version releases built by https://github.com/github/codeql-action/releases
Used by plugin: https://github.com/jenkinsci/codeql-plugin
> Add crawler for codeql-plugin

- sonarqubescannermsbuild.groovy
This reverts commit daae8077811508152b8ecbe9988648102a2286c1, introduced with https://github.com/jenkins-infra/crawler/pull/108.
The impact wasn't thought through. We apologize for the inconvenience, and for breaking some setups. This will get us back to a working state again.
> Revert "Limit number of releases for Scanner for MSBuild (.NET) (#108)"

- consul.groovy
- packer.groovy
- terraform.groovy
Remove the base URL prefix that is being added to the URLs for Hashicorp tools from https://releases.hashicorp.com
It appears that the release page used to have relative URLs, but a recent change (apparently in line with https://www.hashicorp.com/blog/announcing-the-hashicorp-releases-api) has caused the URLs to be absolute
> JENKINS-68486 - Hashicorp plugins unable to download releases

- pom.xml
ref https://github.com/jenkins-infra/crawler/pull/110
from a quick code search I think it's just the version number dependency which is coming from the old core version.
Hard to tell though because it's groovy it could be relying on other deps
> Replace core dependency with version number lib

- Jenkinsfile
Reverts jenkins-infra/crawler#114 as it fails.
Gotta use a shell script instead of inline shell script, but tomorrow.
> Revert "chore(pipeline) fix withEnv interpolation"

- codeql.groovy
[The `v2.6.0-beta.1` release](https://github.com/github/codeql-action/releases/tag/codeql-bundle-v2.6.0-beta.1) (published on 2021-07-27, 3 days after the implementation of this particular crawler 😅) has a different download URL pattern than the other, and throw an error on [the cast to integer filtering out older versions than 2020-08-26](https://github.com/jenkins-infra/crawler/blob/4cd93e6b52475696e5f4d16e389f4e1da3353522/codeql.groovy).
While [the GitHub releases page](https://github.com/github/codeql-action/releases?page=5) returns older releases, [the GitHub API](https://api.github.com/repos/github/codeql-action/releases) used in the script returns only the releases created [on the 2021-05-03](https://github.com/github/codeql-action/releases/tag/codeql-bundle-20210503) or after.
I …
> fix(codeql.groovy): don't try to convert bundle name as integer

- adoptopenjdk.groovy
Adapts [as instructed here](https://api.adoptopenjdk.net) by following the [migration guide](https://api.adoptopenjdk.net/migration.html); namely, by noting that there is now only one `vendor` (`eclipse`) and one `jvm_impl` (`hotspot`). I did not bump https://github.com/jenkins-infra/crawler/blob/f065c6afb641dd49e3443313888315d4e623f3a8/adoptopenjdk.groovy#L39 because the format of the JSON being returned is the same as before; it just has fewer elements now that we are using `api.adoptium.net`, which no longer returns Java 9, 10, 12, 13, 14, 15, or 16 and OpenJ9. I tested this by running the code locally and comparing the JSON before and after, noting that the new JSON was in the same format of the old and was a strict subset of the JDKs returned by the old JSON, which was the expected …
> [JENKINS-66455] Migrate to `api.adoptium.net`

- dotnetSdk.groovy
The support status (short-term vs long-term) is now in a separate `release-type` field in the Microsoft-supplied JSON data, with `support-phase` set to `active` instead of `current` or `lts` like before.
That release type is now retained as a `type` field in the output JSON data.
> dotnetSdk: Update handling for JSON content changes

- scriptler.groovy
The unencrypted git protocol was dropped by GitHub on 2022-03-15.
Fixes #123.
> Adjust GitHub URLs to use https

- dependencycheck.groovy
Fix crawler script to download all GitHub releases when release count exceed the response page size
> [JENKINS-70876] dependency plugin throwing Invalid tool ID

- Jenkinsfile
This PR:
- fixes the File Share synchronization as currently this job is erasing the content uploaded to our update center prototype by our update-center2 test job.
- fixes the folder sync to ensure the content is in the correct destination folder, extracting the SAS token query string from the existing credentials to its own credentials so we can set the destination folder.
- logs each crawler name before executing them.
Note: while aws-cli creates the folder if needed, azcopy fails with a 404 error: I had to manually create the `updates` folder in the File Share.
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/2649
> fix: don't delete existing content on the File Share and fix the destination folder

- grapeConfig.xml
Unlike Maven, Grape/Ivy don't add this automatically.
CC @MarkEWaite
`groovy -Dgrape.config=./grapeConfig.xml ./lib/runner.groovy adoptopenjdk.groovy`
> Add Maven Central to Grape configuration

- sonarqubescannermsbuild.groovy
Added per_page URL parameter as quick fix because versions are currently missing in the Jenkins tools settings page.
Default value is 30 and current amount of releases is 77.
> [sonarqubescannermsbuild.groovy] Added explicit page size to prevent missing releases in the result

- Jenkinsfile
This PR disables CloudFlare to restore prod while we're working on renewing its tokens.
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3968
> chore: comment out CloudFlare sync for now

- Jenkinsfile
Reverts jenkins-infra/crawler#141
Tokens have been renewed, checked via a replay of the crawler job on trusted.ci.jenkins.io.
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3968
> Revert "chore: comment out CloudFlare sync for now"

- Jenkinsfile
This PR replaces the use of a long-lived SAS token by a short-lived one generated from a service principal via the get-fileshare-signed-url script from https://github.com/jenkins-infra/pipeline-library/blob/master/resources/get-fileshare-signed-url.sh
Needs:
- <del>https://github.com/jenkins-infra/jenkins-infra/pull/3323</del> (permanent agent)
- https://github.com/jenkins-infra/packer-images/pull/1084 (ephemeral agents)
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-1952035761
- https://github.com/jenkins-infra/helpdesk/issues/3414#issuecomment-1973817455
> chore: use short-lived SAS token to sync updates-jenkins-io File Share

- adoptopenjdk.groovy
api.adoptium.net may respond with a duplicate release name if a new build was required [1]. In this case, adopt_build_number should be present and incremented.
> Note that they have different adopt_build_number, in effect openjdk_version to Adoptium releases are not 1:1 within the API, and therefore will be grouped into different release lists. As in this case we might re-spin a release, this would modify the adopt_build_number but would map to the same openjdk_version since they are built from the same tag of the OpenJDK repo, and would map to the same version in the upstream project.
[1] https://github.com/adoptium/api.adoptium.net/issues/829
Should fix [JENKINS-72319](https://issues.jenkins.io/browse/JENKINS-72319) Unable to install JDK 21.0.
the current diff is
```bash
❯ rm -r target/ …
```
> Merge JDK release binaries if it shares a release name

- Jenkinsfile
This PR skips azcopy version check which we don't care about as its version is tracked by updatecli.
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3414
> chore: skip azcopy version check

- Jenkinsfile
This PR removes `updates-jenkins-io-file-share-sas-token-query-string` credentials from the pipeline, uperseded by the use of https://github.com/jenkins-infra/pipeline-library/blob/master/resources/get-fileshare-signed-url.sh to get the file share URL including a SAS token.
Verification procedure after merging this PR: ensure crawler job on trusted.ci.jenkins.io still passes.
Next step: delete the corresponding credentials from trusted.ci.jenkins.io
Follow-up of:
- #144 
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3414#issuecomment-2034806598
> cleanup: remove superseded credentials

- .jenkins-scripts/publish.sh
Caught while working on https://github.com/jenkins-infra/helpdesk/issues/4373
Self merging
> chore(publish) fix AWS S3 copy errors by using checksum instead of size

- .jenkins-scripts/publish.sh
Related to https://github.com/jenkins-infra/helpdesk/issues/4402#issuecomment-2506471357
This PR removes all azcopy publication tasks and replace them by rsync.
Note: it also remove the "delete" of remote files in the case of `content` (for mirrorbits) which could create hiccups in some cases
Most of the code comes from
> chore(publish) switch azcopy to rsync tasks

- scriptler.groovy
When checking out the jenkins-scripts repository for the Scriptler catalog, check out from the `main` branch instead of the `master` branch going forward. This change also ensures that all changes should be able to be checked out, regardless of whether a rebase from the upstream repo is possible or not.
> Check out `main` branch for jenkins-scripts

- .jenkins-scripts/publish.sh
as per https://github.com/jenkins-infra/helpdesk/issues/4401
add archives.jenkins.io as a rsync destination to use it as a fallback mirror
> feat(publish): add archives.jenkins.io in the rsync process for update-center in crawler

- .jenkins-scripts/publish.sh
Ref. jenkins-infra/helpdesk#2649 (comment) and jenkins-infra/helpdesk#4610
This change stops copying tools installers to the `pkg` VM since it does not host any update center site anymore.
> chore(publish) stop copying tools metadatas to (aws.)updates.jenkins.io VM (also known as pkg)

- dependencycheck.groovy
The dependency-check repository has been archived on 17/02/2025 and moved from jeremylong user to dependencycheck.
Old https://github.com/jeremylong/DependencyCheck
New location https://github.com/dependency-check/DependencyCheck
I have not been informed of these changes, so the list of available versions remains the one before 17 feb 2025 and version 12.1.0 is the latest available tool in the list.
CC @jeremylong
> Update dependency-check repository URL

- chromedriver.groovy
Not able to run the the selenium Test cases on chrome driver version121
Fixes #139
> Provide latest Chrome Driver releases to tools

- sonarqubescannermsbuild.groovy
Fixes issue #162 where URLs generated for v10 of the SonarScanner for .NET tool were getting matched by the case intended for v1, resulting in invalid links.
Since the [SonarQube Scanner plugin](https://plugins.jenkins.io/sonar/) mentions the JSON files are updated on release of a new version, is there some additional step required to get the crawler script to run off-cycle?
> Restrict case intended for 1.X versions
